version: '3.8'

services:
  gateway: 
    build:
      context: ./gateway
    image: gateway
    volumes:
      - ./gateway/dist:/usr/src/app/dist
    container_name: gateway
    expose:
      - '4000'
    ports:
      - '4000:4000'
  mongo:
    image: mongo
    container_name: mongo
    ports: "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass